### ISSUE TITLE
svc chaos remix ultra not working

### ISSUE THREAD

**Issue by jinx5** [MiSTer-devel/NeoGeo_MiSTer#74]
Will these games like these be fixed to work?
Wanted to play a boss battle with a friend.

**Comment by sorgelig** [comment]
There is no such official game.
Check with those who made this hack, then tweak romsets.xml according to changes.

**Comment by jinx5** [comment]
I put it in. it just loads up garbage. DOesn't work. Used to run a version of it on neorage back in the day. 
It's a version with all the characters unlocked including the boss characters.
There is prob a dozen other games that don't into a glitchy mess. Mostly rom hacks thou.
Wondering if there going to be implemented.

**Comment by Toryalai1** [comment]
Yeah this didn’t work for me. It launched the standard version lol 🤣

**Comment by sorgelig** [comment]
Don't forget to look into UniBIOS cheats. Probably you can unlock/hack something through cheats.

**Comment by protogem2** [comment]
Loading the vanilla SVC Chaos romset with UniBIOS cheats offers a boss unlock function, which makes all midbosses and end bosses available to play as, their character portraits are just invisible on the character select screen. Otherwise, it works fine.

Is the main benefit of this hack to simply provide character portraits on the select screen for the midbosses/bosses or are there other additions?

**Comment by sorgelig** [comment]
ROM works
